name: 🔨 Build, Lint, and Test
description: An action for building, linting, and testing the library
on: 
  workflow_call:
    inputs:
      publish-artifact:
        description: 'A boolean passed from the caller workflow to dictate if we should zip and upload the artifact'
        default: false
        required: false
        type: boolean

jobs:
  build:
    name: 🔨 Build, Lint, and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - run: npm i
        working-directory: my-workspace

      - run: npm run build
        working-directory: my-workspace

      - run: npm run lint
        working-directory: my-workspace

      - if: ${{ inputs.publish-artifact }}
        run: zip -r dist.zip dist
        working-directory: my-workspace

      - if: ${{ inputs.publish-artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: my-workspace/dist
