name: 🔨 Build, Lint, and Test
description: An action for building, linting, and testing the library
on: 
  workflow_call:
    inputs:
      publish-artifact:
        description: 'A boolean passed from the caller workflow to dictate if we should zip and upload the artifact'
        default: false
        required: false
        type: boolean

jobs:
  prereqs:
    name: Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm i
        working-directory: my-workspace


  build:
    name: 🔨 Build, Lint, and Test
    runs-on: ubuntu-latest
    needs: prereqs

    steps:
      - name: Build library
        run: npm run build
        working-directory: my-workspace

      - name: Zip artifact for deployment
        if: ${{ inputs.publish-artifact }}
        run: zip -r dist.zip dist
        working-directory: my-workspace

      - name: Publish pipeline artifact
        if: ${{ inputs.publish-artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: my-workspace/dist
  
  lint:
    name: 🔨 Lint
    runs-on: ubuntu-latest
    needs: prereqs
    steps:
      - name: Lint
        run: npm run lint
        working-directory: my-workspace

  test:
    name: 🔨 Test
    runs-on: ubuntu-latest
    needs: [ build, lint ]
    steps:
      - name: Test
        run: npm run test
        working-directory: my-workspace
