name: Create Prerelease Package

on:
  push:
    branches:
      - main
      - beta

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
        publish-artifact: true

  release:
    needs:
      - build
    uses: ./.github/workflows/release.yml
