name: 🚀 CI&CD

on:
  push:
    branches: [ "main", "beta" ]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      publish-artifact: true

  release:
    needs:
      - build
    uses: ./.github/workflows/release.yml

  recreate-beta:
    uses: ./.github/workflows/create-beta-branch-and-pr.yml
