name: 🔧 Create Beta Branch & PR
description: A workflow on for creating a beta branch and a pull request to main on that branch
on: workflow_call

jobs:
  create-beta:
    name: 🔧 Create Beta Branch & PR
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only run this job when pushing to main
    steps:        
      - name: Check if beta exists
        id: check_beta
        shell: bash
        run: |
            if git ls-remote --exit-code --heads origin beta; then
              echo "exists=true" >> $GITHUB_OUTPUT
            else
              echo "exists=false" >> $GITHUB_OUTPUT
            fi

      - name: Checkout repository
        if: steps.check_beta.outputs.exists == 'false'
        uses: actions/checkout@v4

      - name: 🔧 Create Beta Branch
        if: steps.check_beta.outputs.exists == 'false'
        shell: bash
        run: |
            git fetch origin
            git checkout -b beta origin/main
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit --allow-empty -m "chore: empty commit to enable PR creation"
            git push origin beta

      - name: 🔧 Create PR
        if: steps.check_beta.outputs.exists == 'false'
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
            gh pr create --base main --head beta --title "chore: Promote Beta to Main" --body "Automated PR: This PR promotes the beta branch to main."