name: Create Prerelease Package

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
        publish-artifact: true

  publish:
    uses: ./.github/workflows/publish.yml
    needs:
      - build

  prerelease:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Create Prerelease Package
        run: |
          npx semantic-release --dry-run

