name: Pull Request
description: A workflow that runs for pull requests to the main or beta branches.

on:
  pull_request:
    branches: [ "main", "beta" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./github/actions/build
