name: 🚧 Pull Request
description: A workflow that runs for pull requests to the main or beta branches.

on:
  pull_request:
    branches: [ "main", "beta" ]

jobs:
  check-title:
    uses: ./.github/workflows/enforce-pr-title.yml

  build:
    uses: ./.github/workflows/build.yml
